# xrd.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositebuckets.storage.example.org
spec:
  group: storage.example.org
  names:
    kind: CompositeBucket
    plural: compositebuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  location:
                    type: string
                  storageClass:
                    type: string
                  bucketName:
                    type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositebuckets.storage.example.org
spec:
  compositeTypeRef:
    apiVersion: storage.example.org/v1alpha1
    kind: CompositeBucket
  resources:
  - base:
      apiVersion: storage.gcp.crossplane.io/v1beta1
      kind: Bucket
      spec:
        forProvider:
          location: US
          storageClass: STANDARD
    patches:
    - fromFieldPath: "spec.parameters.location"
      toFieldPath: "spec.forProvider.location"
    - fromFieldPath: "spec.parameters.storageClass"
      toFieldPath: "spec.forProvider.storageClass"
    - fromFieldPath: "spec.parameters.bucketName"
      toFieldPath: "metadata.name"
